---


  - name: Add rotateca script
    template:
      src: rotateca.sh.j2
      dest: "{{ config_dir }}/rotateca.sh"
      mode: "0744"
    run_once: true

  - name: run rotateca.sh
    ansible.builtin.cron:
      name: "rotateca"
      minute: "*"
      hour: "1"
      weekday: "6"
      job: "{{ config_dir }}/rotateca.sh"